In [11]:
import numpy as np

**Ejercicio 1.** Crear un vector con valores entre 20 a 59

In [9]:
array = np.arange(20,60,1)
print(array)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


**Ejericicio 2.** Crear un vector de 25 números aleatorios.

In [15]:
normal2 = np.random.randn(25)
print(normal2)

[-0.70171012 -0.14657414 -0.24374038 -0.66447089 -2.06607765 -0.59450332
 -0.69675889 -0.11517382 -1.06023019  0.0560047  -0.55877475  1.08455983
  0.27577069 -0.88431059  0.98156142  0.90754274  1.18477081  1.14509208
  1.52658753  1.07086401  0.31734999  0.92026834  1.49656998 -0.41379292
 -0.63497927]


**Ejercicio 3.** Crear un vector con los números pares comprendidos entre 20-59

In [12]:
array = np.arange(20,60,2)
print(array)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


**Ejercicio 4.** Crear una matriz 3x3 con valores de 0 a 8

In [ ]:
print(np.full(shape=(3,3), np.arange(0,8,1))) 

[[8 8 8]
 [8 8 8]
 [8 8 8]]


**Ejercicio 5.** Crear una matriz 3x3 con valores entre 5 a 15

**Ejercicio 6.** Crear la matriz identidad de 9x9

**Ejercicio 7.** Crear una matriz 8x8 con unos en los bordes y ceros en el interior

**Ejercicio 8.** Encontrar los indices que no son ceros del array: [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

**Ejercicio 9.** Crear dos vectores al azar A y B, verificar si son iguales

**Ejercicio 10.** Dada una matriz cualquier sumar todos sus elementos

**Ejercicio 11.**  Genera un array de los primeros 23 números pares.

**Ejercicio 12.** Escribe un programa para crar una comparación elemento a elemento de dos matrices dadas.

**Ejercicio 13.** Escribe un programa  para crear una matriz cero 5x5 con elementos en la diagonal principal iguales a 1, 2, 3, 4, 5.