In [2]:
import numpy as np

**Ejercicio 1.** Crear un vector con valores entre 20 a 59

In [9]:
array = np.arange(20,60,1)
print(array)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


**Ejericicio 2.** Crear un vector de 25 números aleatorios.

In [ ]:
vector1 = np.random.randn(25)
# randint(valorMinimo,valorMaximo,numeroDeValores)
vector2 = np.random.randint(0,100,25) 
print(vector1)
print(vector2)

[-0.99008238  0.61200692  0.03186282 -0.31162631  1.52699602  1.18673298
  1.54538604 -0.78776526  0.02918306 -0.05960632  0.49980329 -0.56948802
  0.53284036  0.73909548 -0.34964997  0.86110547 -0.01177411 -0.81213376
  0.99090745  0.49389156 -1.6284303  -0.62276647  0.35256906 -1.58759716
 -0.58097084]
[36 69 90 81 64 86 22 47 49 67 56 25 23 24 57  5 98 60 60 47 89 49 47 72
 69]


**Ejercicio 3.** Crear un vector con los números pares comprendidos entre 20-59

In [12]:
array = np.arange(20,60,2)
print(array)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


**Ejercicio 4.** Crear una matriz 3x3 con valores de 0 a 8

In [ ]:
# np.arange(9) genera un arreglo unidimensional con valores del 0 al 8.
# .reshape(3, 3) convierte este arreglo en una matriz de 3x3.
matriz = np.arange(9).reshape(3, 3)

print(matriz)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Ejercicio 5.** Crear una matriz 3x3 con valores entre 5 a 15

In [28]:
matriz = np.arange(5,14,1).reshape(3,3)
print(matriz)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


**Ejercicio 6.** Crear la matriz identidad de 9x9

In [31]:
# Crear una matriz identidad de 9x9
matriz_identidad = np.eye(9)
print(matriz_identidad) 
# Invertir la matriz horizontalmente
matriz_invertida = np.fliplr(matriz_identidad)
print(matriz_invertida)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Ejercicio 7.** Crear una matriz 8x8 con unos en los bordes y ceros en el interior

In [40]:
# Crear una matriz de 8x8 de unos
matriz = np.ones((8, 8))

# Colocar ceros en el interior (desde la fila y columna 1 hasta la 6)
matriz[1:-1, 1:-1] = 0

print(matriz)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


**Ejercicio 8.** Encontrar los indices que no son ceros del array: [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [60]:
array= [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]
indices = []
for i in range(len(array)):
    if array[i] != 0:
        indices.append(i)

print(indices)

[0, 1, 2, 3, 4, 6, 10, 11, 12, 13, 14]


**Ejercicio 9.** Crear dos vectores al azar A y B, verificar si son iguales

In [59]:
vectorA= np.random.randn(5)
print(vectorA)
vectorB= np.random.randn(5)
print(vectorB)
iguales = np.array_equal(vectorA,vectorB)
print(iguales)

[-0.40802337 -1.55883687  1.35997356  1.07030653 -2.73276753]
[ 1.05788198 -0.98357106  0.60196593 -0.12335537 -0.45700467]
False


**Ejercicio 10.** Dada una matriz cualquier sumar todos sus elementos

**Ejercicio 11.**  Genera un array de los primeros 23 números pares.

In [41]:
# Comienza en 0, termina en 23*2 (46), y saltos de 2 en 2
array = np.arange(0, 23 * 2, 2)
print(array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44]


**Ejercicio 12.** Escribe un programa para crar una comparación elemento a elemento de dos matrices dadas.

**Ejercicio 13.** Escribe un programa  para crear una matriz cero 5x5 con elementos en la diagonal principal iguales a 1, 2, 3, 4, 5.